-- TCBK异常比赛赛果修复SQL
-- 生成时间: 2026-05-09

-- INSERT赛果数据
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039391, 101, 94, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039392, 87, 61, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039393, 89, 93, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039394, 114, 93, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039395, 96, 115, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039396, 89, 62, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039397, 64, 86, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039398, 88, 94, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039399, 131, 122, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039400, 113, 125, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039425, 70, 91, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039426, 68, 67, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039427, 97, 126, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039428, 95, 114, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039429, 101, 100, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039430, 109, 116, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039431, 120, 125, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039432, 99, 93, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039433, 64, 94, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039434, 107, 105, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039435, 140, 89, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039436, 98, 110, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039442, 104, 72, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039443, 79, 85, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039444, 93, 79, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039445, 110, 112, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039446, 98, 78, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039518, 0, 0, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039519, 81, 90, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039520, 84, 98, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039521, 79, 89, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039522, 90, 89, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039523, 97, 98, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039524, 98, 95, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039525, 91, 99, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039526, 102, 104, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039527, 123, 131, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039528, 83, 88, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039529, 84, 82, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039530, 88, 90, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039531, 84, 112, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039532, 71, 85, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039533, 69, 91, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039534, 94, 116, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();
INSERT INTO tcbk_result (match_id, home_score, away_score, created_at, updated_at) VALUES (2039535, 102, 114, NOW(), NOW()) ON DUPLICATE KEY UPDATE home_score=VALUES(home_score), away_score=VALUES(away_score), updated_at=NOW();

-- UPDATE比赛状态为8（已获取赛果）
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039391;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039392;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039393;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039394;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039395;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039396;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039397;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039398;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039399;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039400;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039425;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039426;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039427;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039428;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039429;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039430;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039431;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039432;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039433;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039434;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039435;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039436;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039442;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039443;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039444;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039445;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039446;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039518;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039519;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039520;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039521;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039522;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039523;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039524;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039525;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039526;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039527;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039528;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039529;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039530;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039531;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039532;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039533;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039534;
UPDATE tcbk_match SET match_status = 8 WHERE match_id = 2039535;
